### ISSUE TITLE
Broken link: Page can’t be found error

### ISSUE THREAD

**Issue by TullysInc** [Incubaid/www_incubaid_zola#10]
Incorrect Link: https://www.incubaid.com/projects/wavetwo/ourverses

Correct URL: https://www.incubaid.com/projects/wavetwo/ourverse/

Also, getting a mail delivery error for email: info@incubaid.com

![image](https://github.com/Incubaid/www_incubaid_zola/assets/105203696/b00fbc34-8369-4712-ac28-afaac2b62bd4)

**Comment by sasha-astiadi** [comment]
all deactivated
