### ISSUE TITLE
incubaid mobile optimization v3.10.0

### ISSUE THREAD

**Issue by sasha-astiadi** [Incubaid/www_incubaid_zola#4]
# home

space too much, button too long

<img width="319" alt="Screenshot 2023-05-10 at 18 04 18" src="https://github.com/Incubaid/www_incubaid_zola/assets/43240801/451262a6-1d22-4051-ac9a-d4560437be8f">

texts too big

<img width="329" alt="Screenshot 2023-05-10 at 18 04 39" src="https://github.com/Incubaid/www_incubaid_zola/assets/43240801/30a8838c-ae6f-4956-863b-6592f689dd56">

**Comment by ehab-hassan** [comment]
for the button, if we can make the text shorter will be better
![image](https://github.com/Incubaid/www_incubaid_zola/assets/10484295/1e1cb7d3-eed9-46bb-b728-ce40677c1842)

**Comment by sasha-astiadi** [comment]
make all button size liek the home header size

**Comment by ehab-hassan** [comment]
as we agree in chat I kept the home header button small size at mobile and all have the same size on the desktop
staging and production updated
