### ISSUE TITLE
fix project page

### ISSUE THREAD

**Issue by sasha-astiadi** [Incubaid/www_incubaid_zola#8]
https://www.incubaid.com/projects/wavetwo/

![image](https://github.com/Incubaid/www_incubaid_zola/assets/43240801/72f28cc0-42b2-4a61-864e-a88187d44e94)

- maybe add 'See Projects' button below the wave one, wave two 
(i know the pics are clickable, but we need to make it more obvious)

- ourverse - typo (unclickable)
- 
![image](https://github.com/Incubaid/www_incubaid_zola/assets/43240801/b4e7ea7b-a811-41b2-a8d3-77034af6c7b7)

the correct link should be https://www.incubaid.com/projects/wavetwo/ourverse (remove s at the end)

**Comment by ehab-hassan** [comment]
done at staging
